// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memories.sql

package db

import (
	"context"
	"database/sql"
)

const archiveMemory = `-- name: ArchiveMemory :exec
UPDATE memories
SET
    archived = 1,
    archived_reason = ?,
    superseded_by = ?,
    updated_at = ?
WHERE id = ?
`

type ArchiveMemoryParams struct {
	ArchivedReason sql.NullString `json:"archived_reason"`
	SupersededBy   sql.NullString `json:"superseded_by"`
	UpdatedAt      int64          `json:"updated_at"`
	ID             string         `json:"id"`
}

func (q *Queries) ArchiveMemory(ctx context.Context, arg ArchiveMemoryParams) error {
	_, err := q.db.ExecContext(ctx, archiveMemory,
		arg.ArchivedReason,
		arg.SupersededBy,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const countActiveMemories = `-- name: CountActiveMemories :one
SELECT COUNT(*)
FROM memories
WHERE archived = 0
`

func (q *Queries) CountActiveMemories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveMemories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMemory = `-- name: DeleteMemory :exec
DELETE FROM memories
WHERE id = ?
`

func (q *Queries) DeleteMemory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMemory, id)
	return err
}

const deleteMemoryEventsByMemoryID = `-- name: DeleteMemoryEventsByMemoryID :exec
DELETE FROM memory_events
WHERE memory_id = ?
`

func (q *Queries) DeleteMemoryEventsByMemoryID(ctx context.Context, memoryID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteMemoryEventsByMemoryID, memoryID)
	return err
}

const deleteMemoryEventsOlderThan = `-- name: DeleteMemoryEventsOlderThan :exec
DELETE FROM memory_events
WHERE created_at < ?
`

func (q *Queries) DeleteMemoryEventsOlderThan(ctx context.Context, createdAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteMemoryEventsOlderThan, createdAt)
	return err
}

const getMemory = `-- name: GetMemory :one
SELECT id, scope, kind, preference_category, content, embedding, embedding_model, source, base_weight, access_count, pinned, source_session_id, superseded_by, archived, archived_reason, last_accessed_at, created_at, updated_at
FROM memories
WHERE id = ?
`

func (q *Queries) GetMemory(ctx context.Context, id string) (Memory, error) {
	row := q.db.QueryRowContext(ctx, getMemory, id)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Kind,
		&i.PreferenceCategory,
		&i.Content,
		&i.Embedding,
		&i.EmbeddingModel,
		&i.Source,
		&i.BaseWeight,
		&i.AccessCount,
		&i.Pinned,
		&i.SourceSessionID,
		&i.SupersededBy,
		&i.Archived,
		&i.ArchivedReason,
		&i.LastAccessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMemory = `-- name: InsertMemory :exec
INSERT INTO memories (
    id,
    scope,
    kind,
    preference_category,
    content,
    embedding,
    embedding_model,
    source,
    base_weight,
    access_count,
    pinned,
    source_session_id,
    superseded_by,
    archived,
    archived_reason,
    last_accessed_at,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type InsertMemoryParams struct {
	ID                 string         `json:"id"`
	Scope              string         `json:"scope"`
	Kind               string         `json:"kind"`
	PreferenceCategory string         `json:"preference_category"`
	Content            string         `json:"content"`
	Embedding          []byte         `json:"embedding"`
	EmbeddingModel     sql.NullString `json:"embedding_model"`
	Source             string         `json:"source"`
	BaseWeight         float64        `json:"base_weight"`
	AccessCount        int64          `json:"access_count"`
	Pinned             int64          `json:"pinned"`
	SourceSessionID    sql.NullString `json:"source_session_id"`
	SupersededBy       sql.NullString `json:"superseded_by"`
	Archived           int64          `json:"archived"`
	ArchivedReason     sql.NullString `json:"archived_reason"`
	LastAccessedAt     sql.NullInt64  `json:"last_accessed_at"`
	CreatedAt          int64          `json:"created_at"`
	UpdatedAt          int64          `json:"updated_at"`
}

func (q *Queries) InsertMemory(ctx context.Context, arg InsertMemoryParams) error {
	_, err := q.db.ExecContext(ctx, insertMemory,
		arg.ID,
		arg.Scope,
		arg.Kind,
		arg.PreferenceCategory,
		arg.Content,
		arg.Embedding,
		arg.EmbeddingModel,
		arg.Source,
		arg.BaseWeight,
		arg.AccessCount,
		arg.Pinned,
		arg.SourceSessionID,
		arg.SupersededBy,
		arg.Archived,
		arg.ArchivedReason,
		arg.LastAccessedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertMemoryEvent = `-- name: InsertMemoryEvent :exec
INSERT INTO memory_events (id, memory_id, action, detail, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertMemoryEventParams struct {
	ID        string         `json:"id"`
	MemoryID  sql.NullString `json:"memory_id"`
	Action    string         `json:"action"`
	Detail    string         `json:"detail"`
	CreatedAt int64          `json:"created_at"`
}

func (q *Queries) InsertMemoryEvent(ctx context.Context, arg InsertMemoryEventParams) error {
	_, err := q.db.ExecContext(ctx, insertMemoryEvent,
		arg.ID,
		arg.MemoryID,
		arg.Action,
		arg.Detail,
		arg.CreatedAt,
	)
	return err
}

const listActiveMemories = `-- name: ListActiveMemories :many
SELECT id, scope, kind, preference_category, content, embedding, embedding_model, source, base_weight, access_count, pinned, source_session_id, superseded_by, archived, archived_reason, last_accessed_at, created_at, updated_at
FROM memories
WHERE archived = 0
ORDER BY created_at DESC
`

func (q *Queries) ListActiveMemories(ctx context.Context) ([]Memory, error) {
	rows, err := q.db.QueryContext(ctx, listActiveMemories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.Kind,
			&i.PreferenceCategory,
			&i.Content,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.Source,
			&i.BaseWeight,
			&i.AccessCount,
			&i.Pinned,
			&i.SourceSessionID,
			&i.SupersededBy,
			&i.Archived,
			&i.ArchivedReason,
			&i.LastAccessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePreferencesByCategory = `-- name: ListActivePreferencesByCategory :many
SELECT id, scope, kind, preference_category, content, embedding, embedding_model, source, base_weight, access_count, pinned, source_session_id, superseded_by, archived, archived_reason, last_accessed_at, created_at, updated_at
FROM memories
WHERE archived = 0
  AND kind = 'preference'
  AND preference_category = ?
ORDER BY pinned DESC, updated_at DESC, base_weight DESC, access_count DESC
`

func (q *Queries) ListActivePreferencesByCategory(ctx context.Context, preferenceCategory string) ([]Memory, error) {
	rows, err := q.db.QueryContext(ctx, listActivePreferencesByCategory, preferenceCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.Kind,
			&i.PreferenceCategory,
			&i.Content,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.Source,
			&i.BaseWeight,
			&i.AccessCount,
			&i.Pinned,
			&i.SourceSessionID,
			&i.SupersededBy,
			&i.Archived,
			&i.ArchivedReason,
			&i.LastAccessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedMemoryIDsOlderThan = `-- name: ListArchivedMemoryIDsOlderThan :many
SELECT id
FROM memories
WHERE archived = 1 AND updated_at < ?
ORDER BY updated_at ASC
`

func (q *Queries) ListArchivedMemoryIDsOlderThan(ctx context.Context, updatedAt int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listArchivedMemoryIDsOlderThan, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBaselinePreferences = `-- name: ListBaselinePreferences :many
SELECT id, scope, kind, preference_category, content, embedding, embedding_model, source, base_weight, access_count, pinned, source_session_id, superseded_by, archived, archived_reason, last_accessed_at, created_at, updated_at
FROM memories
WHERE archived = 0
  AND kind = 'preference'
ORDER BY pinned DESC, updated_at DESC, base_weight DESC, access_count DESC
LIMIT ?
`

func (q *Queries) ListBaselinePreferences(ctx context.Context, limit int64) ([]Memory, error) {
	rows, err := q.db.QueryContext(ctx, listBaselinePreferences, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.Kind,
			&i.PreferenceCategory,
			&i.Content,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.Source,
			&i.BaseWeight,
			&i.AccessCount,
			&i.Pinned,
			&i.SourceSessionID,
			&i.SupersededBy,
			&i.Archived,
			&i.ArchivedReason,
			&i.LastAccessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryEvents = `-- name: ListMemoryEvents :many
SELECT id, memory_id, "action", detail, created_at
FROM memory_events
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListMemoryEvents(ctx context.Context, limit int64) ([]MemoryEvent, error) {
	rows, err := q.db.QueryContext(ctx, listMemoryEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryEvent{}
	for rows.Next() {
		var i MemoryEvent
		if err := rows.Scan(
			&i.ID,
			&i.MemoryID,
			&i.Action,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchMemoryAccess = `-- name: TouchMemoryAccess :exec
UPDATE memories
SET
    access_count = access_count + 1,
    last_accessed_at = ?,
    updated_at = ?
WHERE id = ?
`

type TouchMemoryAccessParams struct {
	LastAccessedAt sql.NullInt64 `json:"last_accessed_at"`
	UpdatedAt      int64         `json:"updated_at"`
	ID             string        `json:"id"`
}

func (q *Queries) TouchMemoryAccess(ctx context.Context, arg TouchMemoryAccessParams) error {
	_, err := q.db.ExecContext(ctx, touchMemoryAccess, arg.LastAccessedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateMemory = `-- name: UpdateMemory :exec
UPDATE memories
SET
    kind = ?,
    preference_category = ?,
    content = ?,
    embedding = ?,
    embedding_model = ?,
    base_weight = ?,
    pinned = ?,
    last_accessed_at = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateMemoryParams struct {
	Kind               string         `json:"kind"`
	PreferenceCategory string         `json:"preference_category"`
	Content            string         `json:"content"`
	Embedding          []byte         `json:"embedding"`
	EmbeddingModel     sql.NullString `json:"embedding_model"`
	BaseWeight         float64        `json:"base_weight"`
	Pinned             int64          `json:"pinned"`
	LastAccessedAt     sql.NullInt64  `json:"last_accessed_at"`
	UpdatedAt          int64          `json:"updated_at"`
	ID                 string         `json:"id"`
}

func (q *Queries) UpdateMemory(ctx context.Context, arg UpdateMemoryParams) error {
	_, err := q.db.ExecContext(ctx, updateMemory,
		arg.Kind,
		arg.PreferenceCategory,
		arg.Content,
		arg.Embedding,
		arg.EmbeddingModel,
		arg.BaseWeight,
		arg.Pinned,
		arg.LastAccessedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
