// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package db

import (
	"context"
)

const countSessionsForWorkspace = `-- name: CountSessionsForWorkspace :one
SELECT COUNT(*) AS count
FROM sessions
WHERE workspace_id = ?
`

func (q *Queries) CountSessionsForWorkspace(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionsForWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, name, path)
VALUES (?, ?, ?)
RETURNING id, name, path, created_at
`

type CreateWorkspaceParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Path string `json:"path"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace, arg.ID, arg.Name, arg.Path)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces
WHERE id = ?
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspace, id)
	return err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, path, created_at
FROM workspaces
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceByPath = `-- name: GetWorkspaceByPath :one
SELECT id, name, path, created_at
FROM workspaces
WHERE path = ?
LIMIT 1
`

func (q *Queries) GetWorkspaceByPath(ctx context.Context, path string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByPath, path)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name, path, created_at
FROM workspaces
ORDER BY created_at ASC
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
